### ISSUE TITLE
InitSession Endless Retry Bug

### ISSUE THREAD

**Issue by pwgraham91** [BranchMetrics/android-branch-deep-linking-attribution#798] opened 2020-01-25 00:33 UTC
4.3.1 introduces a bug where if the phone opens a deeplink in the app, calls `initSession` then redirects to another fragment, branch will call `initSession` and redirect to the fragment again and again endlessly.

I tried this with 4.3.0 and 4.2.1 and did not experience this error. This behavior is reproducible and happens every time on 4.3.1

**Comment by echo-branch** [comment] 2020-01-25 00:50
Thanks for the heads up.  We were trying to restore functionality for plugins but was too aggressive about it.

**Comment by bklastaitis-branch** [comment] 2020-01-26 02:12
Thanks for the report @pwgraham91. I'm trying to understand your setup. Would you elaborate on "branch will call initSession"? Do you call `initSession` only from `LauncherActivity.onStart` or elsewhere too?

**Comment by pwgraham91** [comment] 2020-01-27 16:49
@bklastaitis-branch I only call it from `LauncherActivity.onStart`

**Comment by bklastaitis-branch** [comment] 2020-01-27 19:09
@pwgraham91 would you share a sample project or some code snippets that you think are at fault? We are not able to reproduce.

**Comment by pwgraham91** [comment] 2020-01-28 15:52
in `MainActivity.kt`

```
override fun onStart() {
    super.onStart()

    Branch.getInstance().initSession({ referringParams: JSONObject?, error: BranchError? ->
        if (error == null) {

            // takes referringParams and runs code like this:
            val eventHubArgs = EventHubFragmentArgs.Builder(event)
                .setStreamId(streamId)
                .build().toBundle()

            findNavController(R.id.nav_host_fragment).createDeepLink()
                .setDestination(R.id.destination_event_hub)
                .setArguments(eventHubArgs)
                .createTaskStackBuilder()
                .startActivities()
        }
        }
    }, this)
}
```

**Comment by bklastaitis-branch** [comment] 2020-01-29 19:21
@pwgraham91 thank you again! We made a ticket to fix it (SDK-784), the next release, v4.3.2, is expected is this week.

**Comment by pwgraham91** [comment] 2020-01-29 20:16
I appreciate the quick turnaround!

**Comment by echo-branch** [comment] 2020-02-10 21:34
Should be fixed in latest release.

**Closed by echo-branch** 2020-02-10 21:34 UTC
