### ISSUE TITLE
Branch being down or incorrect branch setup causes app to ANR / drop frames

### ISSUE THREAD

**Issue by hordurhauks** [BranchMetrics/android-branch-deep-linking-attribution#907] opened 2021-04-29 14:54 UTC
I had a problem where my app was suddenly very slow, i.e. massive frame drops on every screen. I realised that one of our developers changed the branch key so my branch setup was incorrect. After updating the key in the app, it stopped dropping frames. 

Now, Branch seems to be down as I can see multiple calls to https://api2.branch.io/v1/open returning http code 500 in the android profiler. This causes the app to start dropping frames again.

This issue makes branch unusable since we don't want to rely on branch to be up for our app to not drop frames. There must be something really wrong in the library.

This happens on version 5.0.7. Downgrading to 5.0.3 seems to fix the issue.

**Comment by TheZebraz** [comment] 2021-04-29 15:12
Have same issue! 
Branch prints stack trace and freeze application.
![image](https://user-images.githubusercontent.com/7344776/116574331-46f88980-a916-11eb-83e9-bf0e033d647d.png)

**Comment by jd565** [comment] 2021-04-29 15:13
From a quick look through the code Branch is launching an AsyncTask to make a network request, but awaiting on a Latch until the network request is done (or the latch times out) - if your session never initialises (because the API is down) then their APK will call this code on the main thread every time an activity is resumed.

It seems like this code was added some time between 5.0.3 and 5.0.7 (the latch has disappeared when going back to 5.0.3), so would suggest people downgrade until Branch sorts this out.

**Comment by hatched-mariusz** [comment] 2021-04-29 15:18
5.0.4 works too

**Comment by jd565** [comment] 2021-04-29 15:21
At some point they added the latch but ran it in a separate thread. Then in https://github.com/BranchMetrics/android-branch-deep-linking-attribution/commit/69f7d35f21a27286435b6ed1bd63042bbec8fe7d they changed the latch to run in the current thread.

This commit happened on 18th Feb, so anything before then is probably OK

**Comment by vhontar** [comment] 2021-04-29 15:35
Production app is dying because of that.
https://status.branch.io/#day

**Comment by echo-branch** [comment] 2021-04-29 16:03
Looking into this one now.

**Comment by echo-branch** [comment] 2021-04-29 17:40
Confirmed the bug, going to try to get a patch release today.

**Comment by bklastaitis-branch** [comment] 2021-04-30 17:26
5.0.8 should fix the issue now.

**Comment by jf-branch** [comment] 2021-10-17 06:16
Closing this out due to 5.0.8 release fix. 

Thank you for bringing this to our attention!

**Closed by jf-branch** 2021-10-17 06:16 UTC
